version: '3.8'

services:
  db:
    image: postgres:16.1-alpine3.18
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G


  perf_web_app_template:
    build:
      context: ./javabase/classic_orm
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  java_classic_orm:
    build:
      dockerfile: Dockerfile
    extends:
      service: perf_web_app_template
    ports:
      - '8081:8080'
  java_classic_orm_native:
    build:
      dockerfile: Dockerfile.native
    extends:
      service: perf_web_app_template
    ports:
      - '8082:8080'